ROAD_WIDTH = 8.0
NUM_CONTROL_NODES = 8
NUM_SAMPLED_POINTS = 20
MAX_ANGLE = 270
MIN_ANGLE = 20
SEG_LENGTH = 25

MAX_EPISODE_STEPS = 2000

IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS = 160, 320, 3
INPUT_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS)

DISPLACEMENT = 2

AGENT_TYPES = ["random", "supervised", "autopilot"]
